import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  footerContainer: {
    borderTopWidth: 1,
    borderTopColor: "#eee",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: Platform.select({ ios: 10, android: 8 }),
    paddingHorizontal: 5,
  },
  footerItem: {
    alignItems: "center",
    justifyContent: "center",
    padding: 8,
    position: "relative",
    minWidth: 60,
  },
  footerText: {
    fontSize: 12,
    color: "#00468b",
    marginTop: 4,
    fontWeight: "500",
  },
  footerTextInactive: {
    fontSize: 12,
    color: "#aaa",
    marginTop: 4,
  },
  activeDot: {
    width: 4,
    height: 4,
    backgroundColor: "#00468b",
    borderRadius: 2,
    position: "absolute",
    bottom: 0,
  },
  aiButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 30,
    marginTop: -10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 5,
    width: 60,
    height: 60,
  },
  popupMenu: {
    position: "absolute",
    bottom: 70,
    backgroundColor: "#fff",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 0,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 100,
  },
  popupButton: {
    alignItems: "center",
    marginHorizontal: 8,
    padding: 5,
  },
  popupText: {
    fontSize: 10,
    color: "#00468b",
    marginTop: 2,
    fontWeight: "500",
  },
  animationContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: 80,
    height: 80,
  },
  rainbowBackground: {
    position: "absolute",
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  circle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#00468b",
    zIndex: 1,
  },
  speakingAnimationContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: 60,
    zIndex: 1,
  },
  oval: {
    width: 10,
    height: 20,
    borderRadius: 5,
    backgroundColor: "#1E3A8A",
    marginHorizontal: 2,
  },
});