import { StyleSheet, Platform } from "react-native";

export const pickerSelectStyles = {
  inputIOS: {
    fontSize: 16,
    color: "#2D3748",
  },
  inputAndroid: {
    fontSize: 16,
    color: "#2B6CB0",
  },
  placeholder: {
    color: "#A0AEC0",
  },
};

const styles = StyleSheet.create({
  fullscreenLoader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  loadingAnimation: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  scrollContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginTop: 50,
    marginBottom: 30,
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 180,
    backgroundColor: '#3182CE',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    zIndex: -1,
  },
  icon: {
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#007AFF",
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: "#007AFF",
    marginTop: 8,
    textAlign: 'center',
  },
  loaderContainer: {
    alignItems: "center",
    marginVertical: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#fff",
    fontWeight: '500',
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(254, 215, 215, 0.9)",
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  errorText: {
    marginLeft: 10,
    color: "#C53030",
    fontSize: 14,
    flex: 1,
  },
  errorContent: {
    flex: 1,
    marginLeft: 10,
  },
  formContainer: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 15,
    marginTop: 5,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4A5568",
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelIcon: {
    marginRight: 6,
  },
  pickerContainer: {
    backgroundColor: "#EDF2F7",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  plateContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EBF8FF",
    padding: 16,
    borderRadius: 12,
    marginTop: 15,
    borderWidth: 1,
    borderColor: '#BEE3F8',
  },
  plateLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2B6CB0",
    marginLeft: 10,
  },
  plateNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: "#2B6CB0",
    marginLeft: 6,
  },
  button: {
    backgroundColor: "#3182CE",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 25,
    justifyContent: "center",
    flexDirection: "row",
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  buttonInner: {
    flexDirection: "row",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 8,
  },
  recentSelectionsContainer: {
    marginBottom: 20,
  },
  recentSelectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 12,
  },
  recentSelectionScroll: {
    paddingBottom: 8,
  },
  recentSelectionItem: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginRight: 12,
    width: 250, // Fixed width instead of percentage
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  recentSelectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  recentSelectionRoute: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3748',
    marginLeft: 8,
  },
  recentSelectionDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recentSelectionBusInfo: {
    fontSize: 14,
    color: '#718096',
  },
  useThisButton: {
    backgroundColor: '#EBF8FF',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginTop: 8,
  },
  useThisButtonText: {
    color: '#3182CE',
    fontSize: 12,
    fontWeight: '600',
  },
  mapPreviewContainer: {
    height: 150,
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 15,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  mapPlaceholder: {
    backgroundColor: '#EDF2F7',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPlaceholderText: {
    color: '#718096',
    fontSize: 14,
  },
  mapActionButton: {
    backgroundColor: '#EDF2F7',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignSelf: 'flex-end',
    margin: 8,
  },
  mapActionButtonText: {
    color: '#718096',
    fontSize: 12,
    fontWeight: '500',
  },
  showMapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF8FF',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignSelf: 'center',
    marginVertical: 10,
  },
  showMapButtonText: {
    color: '#3182CE',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 6,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF2F7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D3748',
    marginLeft: 8,
    paddingVertical: 4,
  },
  clearButton: {
    padding: 4,
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  stepItem: {
    alignItems: 'center',
    width: 60, // Fixed width instead of percentage
  },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  stepCircleActive: {
    backgroundColor: '#3182CE',
  },
  stepCircleCompleted: {
    backgroundColor: '#48BB78',
  },
  stepNumber: {
    color: '#718096',
    fontWeight: '600',
  },
  stepNumberActive: {
    color: '#fff',
  },
  stepLabel: {
    fontSize: 12,
    color: '#718096',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#3182CE',
    fontWeight: '500',
  },
  stepConnector: {
    height: 3,
    backgroundColor: '#E2E8F0',
    flex: 1,
    marginTop: 15,
  },
  stepConnectorActive: {
    backgroundColor: '#3182CE',
  },
});

export default styles;
