import { StyleSheet, Platform } from "react-native";

export const pickerSelectStyles = {
  inputIOS: {
    fontSize: 16,
    color: "#2D3748",
  },
  inputAndroid: {
    fontSize: 16,
    color: "#2B6CB0",
  },
  placeholder: {
    color: "#A0AEC0",
  },
};

const styles = StyleSheet.create({
  fullscreenLoader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  loadingAnimation: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  scrollContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 180,
    backgroundColor: '#3182CE',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    zIndex: -1,
  },
  icon: {
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#007AFF",
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: "#007AFF",
    marginTop: 8,
    textAlign: 'center',
  },
  loaderContainer: {
    alignItems: "center",
    marginVertical: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#fff",
    fontWeight: '500',
  },
  errorContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#EDF2F7",
  },
  errorText: {
    marginLeft: 10,
    color: "#C53030",
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  errorContent: {
    flex: 1,
  },
  formContainer: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 15,
    marginTop: 5,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4A5568",
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelIcon: {
    marginRight: 6,
  },
  pickerContainer: {
    backgroundColor: "#EDF2F7",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  plateContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EBF8FF",
    padding: 16,
    borderRadius: 12,
    marginTop: 15,
    borderWidth: 1,
    borderColor: '#BEE3F8',
  },
  plateLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2B6CB0",
    marginLeft: 10,
  },
  plateNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: "#2B6CB0",
    marginLeft: 6,
  },
  button: {
    backgroundColor: "#007AFF",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 25,
    justifyContent: "center",
    flexDirection: "row",
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  buttonInner: {
    flexDirection: "row",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 8,
  },
  recentSelectionsContainer: {
    marginBottom: 20,
  },
  recentSelectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 12,
  },
  recentSelectionScroll: {
    paddingBottom: 8,
  },
  recentSelectionItem: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginRight: 12,
    width: 250, // Fixed width instead of percentage
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  recentSelectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  recentSelectionRoute: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3748',
    marginLeft: 8,
  },
  recentSelectionDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recentSelectionBusInfo: {
    fontSize: 14,
    color: '#718096',
  },
  useThisButton: {
    backgroundColor: '#EBF8FF',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginTop: 8,
  },
  useThisButtonText: {
    color: '#3182CE',
    fontSize: 12,
    fontWeight: '600',
  },
  mapPreviewContainer: {
    borderRadius: 16,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#BEE3F8',
    backgroundColor: '#F7FAFC',
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  mapPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    backgroundColor: '#EBF8FF',
    borderBottomWidth: 1,
    borderBottomColor: '#BEE3F8',
  },
  mapPlaceholderText: {
    color: '#2C5282',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 8,
  },
  routeContainer: {
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
  },
  routeStationContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
    position: 'relative',
  },
  routeLine: {
    width: 2,
    backgroundColor: '#3182CE',
    marginHorizontal: 4,
    flex: 0,
    position: 'absolute',
    top: 15,
    bottom: -16,
    left: 6,
    zIndex: 1,
  },
  routeStationDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#3182CE',
    marginTop: 2,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 2,
    zIndex: 2,
  },
  routeStationDotStart: {
    backgroundColor: '#38A169',
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  routeStationDotEnd: {
    backgroundColor: '#E53E3E',
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  routeStationDotIntermediate: {
    backgroundColor: '#3182CE',
    width: 14,
    height: 14,
    borderRadius: 7,
    marginHorizontal:4,
  },
  routeStationContent: {
    flex: 1,
    paddingLeft: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 2,
  },
  routeStationName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3748',
    marginBottom: 4,
  },
  routeStationNameIntermediate: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4A5568',
  },
  routeStationInfo: {
    fontSize: 12,
    color: '#718096',
    marginBottom: 4,
    backgroundColor: '#F7FAFC',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  mapActionButton: {
    backgroundColor: '#EDF2F7',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: 'center',
    marginVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  mapActionButtonText: {
    color: '#4A5568',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  showMapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EBF8FF',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignSelf: 'center',
    marginVertical: 12,
    borderWidth: 1,
    borderColor: '#BEE3F8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  showMapButtonText: {
    color: '#3182CE',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF2F7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D3748',
    marginLeft: 8,
    paddingVertical: 4,
  },
  clearButton: {
    padding: 4,
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  stepItem: {
    alignItems: 'center',
    width: 60, // Fixed width instead of percentage
  },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  stepCircleActive: {
    backgroundColor: '#3182CE',
  },
  stepCircleCompleted: {
    backgroundColor: '#48BB78',
  },
  stepNumber: {
    color: '#718096',
    fontWeight: '600',
  },
  stepNumberActive: {
    color: '#fff',
  },
  stepLabel: {
    fontSize: 12,
    color: '#718096',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#3182CE',
    fontWeight: '500',
  },
  stepConnector: {
    height: 3,
    backgroundColor: '#E2E8F0',
    flex: 1,
    marginTop: 15,
  },
  stepConnectorActive: {
    backgroundColor: '#3182CE',
  },
  // Search Results Styles
  searchResultsContainer: {
    marginTop: 12,
    marginBottom: 16,
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchResultsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#3182CE',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  searchResultContent: {
    flex: 1,
    paddingRight: 8,
  },
  searchResultRoute: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2C5282',
    marginBottom: 6,
  },
  searchResultBus: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4A5568',
    marginBottom: 4,
  },
  searchResultLocation: {
    fontSize: 13,
    color: '#718096',
    flexDirection: 'row',
    alignItems: 'center',
  },
  moreResultsText: {
    fontSize: 13,
    color: '#718096',
    fontStyle: 'italic',
    marginTop: 8,
    textAlign: 'center',
    backgroundColor: '#EDF2F7',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'center',
  },
});

export default styles;
